# Generated by Django 3.0.5 on 2020-10-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
